### ISSUE TITLE
Compilation problem ?

### ISSUE THREAD

**Issue by BastienV-SATIE** [skjafar/Portenta_Cube_Template#2]
I'm trying to build the CM7 projet but I have a lot of problems.
(the CM4 project is compiling without any issue)
I must be making something wrong.

18:09:23 **** Incremental Build of configuration Debug for project portenta_STM_template_CM7 ****
make -j32 all 
arm-none-eabi-gcc -o "portenta_STM_template_CM7.elf" @"objects.list"   -mcpu=cortex-m7 -T"/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/STM32H747XIHX_FLASH.ld" --specs=nosys.specs -Wl,-Map="portenta_STM_template_CM7.map" -Wl,--gc-sections -static --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -u _printf_float -Wl,--start-group -lc -lm -Wl,--end-group
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./USB_DEVICE/App/usbd_cdc_if.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/console.h:24: multiple definition of `xCreatedAppUSBInfoTask'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/console.h:24: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./USB_DEVICE/App/usbd_cdc_if.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/console.h:23: multiple definition of `xCreatedAppUSBCLITask'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/console.h:23: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/FreeRTOSTimer.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../../Common/header/registers.h:15: multiple definition of `REGS'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../../Common/header/registers.h:15: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/TCPConsole.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:19: multiple definition of `TCP_CLITaskNumber'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:19: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/TCPConsole.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:18: multiple definition of `USBTaskNumber'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:18: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/TCPConsole.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:17: multiple definition of `controllingTaskNumber'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:17: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/TCPIP.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../../Common/header/parameters.h:14: multiple definition of `PARS'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../../Common/header/parameters.h:14: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/TCPIP.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:19: multiple definition of `TCP_CLITaskNumber'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:19: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/TCPIP.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:18: multiple definition of `USBTaskNumber'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:18: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/TCPIP.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:17: multiple definition of `controllingTaskNumber'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:17: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/application_commands.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../../Common/header/registers.h:15: multiple definition of `REGS'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../../Common/header/registers.h:15: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/application_commands.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../../Common/header/parameters.h:14: multiple definition of `PARS'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../../Common/header/parameters.h:14: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/application_commands.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:19: multiple definition of `TCP_CLITaskNumber'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:19: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/application_commands.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:18: multiple definition of `USBTaskNumber'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:18: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/application_commands.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:17: multiple definition of `controllingTaskNumber'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:17: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/console.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../../Common/header/registers.h:15: multiple definition of `REGS'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../../Common/header/registers.h:15: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/console.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:19: multiple definition of `TCP_CLITaskNumber'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:19: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/console.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:18: multiple definition of `USBTaskNumber'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:18: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/console.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:17: multiple definition of `controllingTaskNumber'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:17: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/console.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/console.h:24: multiple definition of `xCreatedAppUSBInfoTask'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/console.h:24: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/console.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/console.h:23: multiple definition of `xCreatedAppUSBCLITask'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/console.h:23: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/parameters.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:19: multiple definition of `TCP_CLITaskNumber'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:19: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/parameters.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:18: multiple definition of `USBTaskNumber'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:18: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/parameters.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:17: multiple definition of `controllingTaskNumber'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:17: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/parameters.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../../Common/header/parameters.h:14: multiple definition of `PARS'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../../Common/header/parameters.h:14: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/registers.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:19: multiple definition of `TCP_CLITaskNumber'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:19: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/registers.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:18: multiple definition of `USBTaskNumber'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:18: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/registers.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:17: multiple definition of `controllingTaskNumber'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../application/header/application_commands.h:17: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/registers.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../../Common/header/parameters.h:14: multiple definition of `PARS'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../../Common/header/parameters.h:14: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/registers.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../../Common/header/registers.h:15: multiple definition of `REGS'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../../Common/header/registers.h:15: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/shared_data.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../../Common/header/registers.h:15: multiple definition of `REGS'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../../Common/header/registers.h:15: first defined here
/home/bastien/Applications/stm32cubeide_1.10.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.0.202111181127/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./application/source/shared_data.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../../Common/header/parameters.h:14: multiple definition of `PARS'; ./Core/Src/main.o:/home/bastien/STM32CubeIDE/workspace_1.10.1/Portenta_Cube_Template-master/CM7/Debug/../../Common/header/parameters.h:14: first defined here
collect2: error: ld returned 1 exit status
make: *** [makefile:79: portenta_STM_template_CM7.elf] Error 1
"make -j32 all" terminated with exit code 2. Build might be incomplete.

18:09:24 Build Failed. 33 errors, 0 warnings. (took 520ms)

**Comment by skjafar** [comment]
This is an issue caused by my bad programming habits.
gcc had no problem with global functions even when they are not defined extern, with the later gcc versions this is promoted from warning to error.

This problem should be fixed now.

I have also updated the code to the latest firmware and it was tested on STM32CubeIDE v1.10.1
